### ISSUE TITLE
The link to the dataset is not available

### ISSUE THREAD

**Issue by Aegon007** [lsvih/CUMUL#1]
Hi, I think the link to the dataset is not available, could you update the link?

**Comment by lsvih** [comment]
Sorry to hear that but I didn't keep this dataset locally. Seems the website is temporarily down, maybe we can send an email to remind the author.

**Comment by vs5938** [comment]
Yeah, the dataset is still not available. :/

**Comment by lsvih** [comment]
hi there I find an achieve of original webpage  https://web.archive.org/web/20180716181420/http://lorre.uni.lu/~andriy/zwiebelfreunde/
